// Generated by CoffeeScript 1.8.0
(function() {
  exports.lexer = require('./lexer');

  exports.parser = require('./parser');

  exports.nodes = require('./nodes');

  exports.parse = function(sql, callingComponent) {
    if ([null, undefined].includes(callingComponent)) {
      return exports.parser.parse(exports.lexer.tokenize(sql));
    } 
    else {
      return exports.parser.parse(exports.lexer.tokenize(sql, {}, "physicalDesigner"));
    }
  };

}).call(this);
